### ISSUE TITLE
Compiling fails with 32 bits compiler (GCC)

### ISSUE THREAD

**Issue by rdjondo** [abenkhadra/spedi#2]
To reproduce the issue, try compiling with a 32 bits compiler, i.e. with cygwin 32 bits on Windows or a Raspberry Pi running debian.

**Comment by abenkhadra** [comment]
Unfortunately, I do not have time to support Spedi for the time being. However, I can help in case you have issues reproducing the results published in our paper. 

Please note that our experiments were conducted on an x86-64 machine running Ubuntu 16.04. Spedi requires a c++14 compiler (although a c++11 compiler should do with minor source changes). The benchmarks are available [here](https://github.com/abenkhadra/cases16-benchmarks).
